# Generated by Django 4.2.6 on 2024-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='payment',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('CD', 'Cash on Delivery'), ('PP', 'Paypal')], default='Cash on Delivery', max_length=2),
        ),
    ]
