# Generated by Django 4.2.6 on 2024-10-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shipping_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('CD', 'Cash on Delivery'), ('PP', 'Paypal')], default='Cash on Delivery', max_length=2),
        ),
    ]
