# Generated by Django 4.2.6 on 2024-10-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_shipping_payment_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey( null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.shipping'),
            preserve_default=False,
        ),
    ]
