# Generated by Django 4.2.6 on 2024-11-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='orderitem',
        ),
    ]
